ports:
- port: 8080
  onOpen: open-preview
tasks:
- init: >
    python3 -m pip install -r requirements.txt &&
    cd mysite &&
    python3 manage.py migrate
  command: >
    echo "from mysite.settings import *" > mysite/local_settings.py &&
    echo "ALLOWED_HOSTS = ['*']" >> mysite/local_settings.py &&
    export DJANGO_SETTINGS_MODULE=mysite.local_settings &&
    python3 manage.py runserver 0.0.0.0:8080
github:
    prebuilds:
        pullRequestsFromForks: true